### ISSUE TITLE
tinkers construct

### ISSUE THREAD

**Issue by bookerthegeek** [TheLMiffy1111/JAOPCA#102]
# Heyo # 
Saw this in the logs. Thought you might want to know.

```
java.lang.NoSuchMethodException: slimeknights.tconstruct.common.TinkerOredict.doTheOredict(net.minecraftforge.fml.common.event.FMLInitializationEvent)
	at java.lang.Class.getDeclaredMethod(Unknown Source)
	at thelm.oredictinit.compat.CompatTinkersConstruct.register(CompatTinkersConstruct.java:19)
	at thelm.oredictinit.registry.OreDictRegisCore.initCompat(OreDictRegisCore.java:18)
	at thelm.oredictinit.lib.EventHandler.onRegistryWrapUp(EventHandler.java:24)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1342_EventHandler_onRegistryWrapUp_Event0.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:97)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_733_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:787)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

### Versions ###
- tconstruct-1.12.2-2.11.0.106
- jaopca-1.12.2-2.2.8.100

**Comment by LemADEC** [comment]
Issue is still reproduced with
TConstruct-1.12.2-2.12.0.135
JAOPCA-1.12.2-2.2.8.101

**Comment by Macleykun** [comment]
Dear @TheLMiffy1111 

Sorry for reviving this issue, but I noticed this issue aswell with the most recent TConstruct and JAOPCA mods on 1.12.2.

May i ask if it's possible to look at this issue and perhaps implement a fix for this?

I've asked the people @ TConstruct if they can fix it, but have recieved the following answer:

> JAOPCA is calling one of our internal methods. Its not in our API, so any errors with calling it are on them.

Reported issue: https://github.com/SlimeKnights/TinkersConstruct/issues/4422

It seems that JAOPCA actually doesn't have to call the methodes from TConstruct. So perhaps it's an easy fix?

Looking forward to your reply!

Versions tested:
TConstruct-1.12.2-2.13.0.183.jar
JAOPCA-1.12.2-2.2.8.104.jar

**Comment by Macleykun** [comment]
Thanks for reopening!

**Comment by Macleykun** [comment]
Thanks for fixing this so fast! Looking forward to the next update to forge!
https://github.com/TheLMiffy1111/JAOPCA/commit/5b6b2360049d8ef6e07b6940b3ffc43ecfec4bbf
