### ISSUE TITLE
Crash when TC's smeltery module is disabled

### ISSUE THREAD

**Issue by TheFurtivePygmy** [TheLMiffy1111/JAOPCA#15]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.6.0.jar)
  LoadingPlugin (Quark-r1.2-93.jar)
  IvToolkit (IvToolkit-1.3.3.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.1-anarchy.jar)
  CTMCorePlugin (CTM-MC1.11.2-0.2.1.10.jar)
  CoFH Loading Plugin (CoFHCore-1.11.2-4.2.7.15-universal.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
  AstralCore (astralsorcery-1.4.5.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 7/31/17 2:54 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from JAOPCA (jaopca)
Caused by: java.lang.NullPointerException
	at slimeknights.mantle.util.RecipeMatch$ItemCombination.<init>(RecipeMatch.java:222)
	at slimeknights.mantle.util.RecipeMatch.ofNBT(RecipeMatch.java:112)
	at slimeknights.mantle.util.RecipeMatch.ofNBT(RecipeMatch.java:108)
	at slimeknights.tconstruct.smeltery.TinkerSmeltery.registerOredictMeltingCasting(TinkerSmeltery.java:717)
	at thelm.jaopca.modules.ModuleTinkersConstruct.init(ModuleTinkersConstruct.java:32)
	at thelm.jaopca.registry.RegistryCore.registerInit(RegistryCore.java:440)
	at thelm.jaopca.registry.RegistryCore.init(RegistryCore.java:89)
	at thelm.jaopca.JAOPCA.secondMovement(JAOPCA.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:647)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:828)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:357)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:521)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_141, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 384037912 bytes (366 MB) / 990633984 bytes (944 MB) up to 3207856128 bytes (3059 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.1.2414 62 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.1.2414.jar) 
	UCHI	forge{13.20.1.2414} [Minecraft Forge] (forge-1.11.2-13.20.1.2414.jar) 
	UCHI	ivtoolkit{1.3.3} [IvToolkit] (minecraft.jar) 
	UCHI	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHI	foamfixcore{7.7.4} [FoamFixCore] (minecraft.jar) 
	UCHI	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-3.0.0.284-universal.jar) 
	UCHI	aether_legacy{v1.0.1} [Aether Legacy] (aether_legacy-1.11.2-1.0.1.jar) 
	UCHI	akashictome{1.1-7} [Akashic Tome] (AkashicTome-1.1-7.jar) 
	UCHI	jei{4.5.0.293} [Just Enough Items] (jei_1.11.2-4.5.0.293.jar) 
	UCHI	appleskin{1.0.7} [AppleSkin] (AppleSkin-mc1.11-1.0.7.jar) 
	UCHI	astralsorcery{1.4.5} [Astral Sorcery] (astralsorcery-1.4.5.jar) 
	UCHI	atg{2} [Alternate Terrain Generation] (atg-1.11.2-2.1.7.jar) 
	UCHI	quark{r1.2-93} [Quark] (Quark-r1.2-93.jar) 
	UCHI	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UCHI	baubles{1.4.5} [Baubles] (Baubles-1.11-1.4.5.jar) 
	UCHI	bibliocraft{2.3.3} [BiblioCraft] (BiblioCraft[v2.3.3][MC1.11.2].jar) 
	UCHI	biomesoplenty{6.2.0.2267} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.2.0.2267-universal.jar) 
	UCHI	bibliowoodsbop{2.0} [BiblioWoodBoP] (BiblioWoods[BiomesOPlenty][v2.0][MC1.11.2].jar) 
	UCHI	bibliowoodsforestry{2.0} [BiblioWoodForestry] (BiblioWoods[Forestry][v2.0][MC1.11.2].jar) 
	UCHI	forestry{5.3.4.155} [Forestry] (forestry_1.11.2-5.3.4.155.jar) 
	UCHI	binniecore{2.1.0.22} [Binnie Core] (binnie-mods-1.11.2-2.1.0.22.jar) 
	UCHI	botany{2.1.0.22} [Binnie's Botany] (binnie-mods-1.11.2-2.1.0.22.jar) 
	UCHI	extrabees{2.1.0.22} [Binnie's Extra Bees] (binnie-mods-1.11.2-2.1.0.22.jar) 
	UCHI	extratrees{2.1.0.22} [Binnie's Extra Trees] (binnie-mods-1.11.2-2.1.0.22.jar) 
	UCHI	genetics{2.1.0.22} [Binnie's Genetics] (binnie-mods-1.11.2-2.1.0.22.jar) 
	UCHI	guideapi{1.11.2-2.1.4-56} [Guide-API] (Guide-API-1.11.2-2.1.4-56.jar) 
	UCHI	bloodmagic{1.11-2.1.11-80} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.11-80.jar) 
	UCHI	botania{r1.9-345} [Botania] (Botania r1.9-345.jar) 
	UCHI	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCHI	codechickenlib{3.0.0.284} [CodeChicken Lib] (CodeChickenLib-1.11.2-3.0.0.284-universal.jar) 
	UCHI	chickenchunks{2.3.1.68} [ChickenChunks] (ChickenChunks-1.11.2-2.3.1.68-universal.jar) 
	UCHI	chisel{MC1.11.2-0.0.13.22} [Chisel] (Chisel-MC1.11.2-0.0.13.22.jar) 
	UCHI	chiselsandbits{13.12} [Chisels & Bits] (chiselsandbits-13.12.jar) 
	UCHI	cofhcore{4.2.7} [CoFH Core] (CoFHCore-1.11.2-4.2.7.15-universal.jar) 
	UCHI	ctm{MC1.11.2-0.2.1.10} [CTM] (CTM-MC1.11.2-0.2.1.10.jar) 
	UCHI	dsurround{3.4.6.0} [Dynamic Surroundings] (DynamicSurroundings-1.11.2-3.4.6.0.jar) 
	UCHI	presets{3.4.6.0} [Presets!] (DynamicSurroundings-1.11.2-3.4.6.0.jar) 
	UCHI	embers{0.220} [Embers] (embers-0.220.jar) 
	UCHI	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHI	foamfix{@VERSION@} [FoamFix] (foamfix-0.7.1-anarchy.jar) 
	UCHI	fw{1.5.0} [Fullscreen Windowed] (FullscreenWindowed-1.10.2-1.5.0.jar) 
	UCHI	mantle{1.11.2-1.2.0.26} [Mantle] (Mantle-1.11.2-1.2.0.26.jar) 
	UCHI	tconstruct{1.11.2-2.7.1.34} [Tinkers' Construct] (TConstruct-1.11.2-2.7.1.34.jar) 
	UCHI	immersiveengineering{0.11-63} [Immersive Engineering] (ImmersiveEngineering-0.11-63.jar) 
	UCHI	immersivepetroleum{1.1.2} [Immersive Petroleum] (immersivepetroleum-1.11.2-1.1.2.jar) 
	UCHI	journeymap{1.11.2-5.4.7} [JourneyMap] (journeymap-1.11.2-5.4.7.jar) 
	UCHI	nex{1.1.10.11} [NetherEx] (NetherEx-1.11.2-1.1.10.11.jar) 
	UCHI	reccomplex{1.4.4-1.11} [Recurrent Complex] (RecurrentComplex-1.4.4-1.11.jar) 
	UCHI	roots{0.025} [Roots 2] (roots-2-0.025.jar) 
	UCHI	storagedrawers{1.11.2-4.2.10} [Storage Drawers] (StorageDrawers-1.11.2-4.2.10.jar) 
	UCHI	storagedrawersextra{@VERSION@} [Storage Drawers Extras] (StorageDrawersExtras-1.11.2-2.0.0.jar) 
	UCHI	thermalfoundation{2.2.5} [Thermal Foundation] (ThermalFoundation-1.11.2-2.2.5.16-universal.jar) 
	UCHI	thermalexpansion{5.2.6} [Thermal Expansion] (ThermalExpansion-1.11.2-5.2.6.22-universal.jar) 
	UCHI	tombmanygraves{1.11.2-3.0.10} [Tomb Many Graves] (TombManyGraves-1.11.2-3.0.10.jar) 
	UCHI	waila{1.7.1} [waila] (Waila-1.7.1_1.11.2.jar) 
	UCHI	wanionlib{1.11.2-1.1} [WanionLib] (WanionLib-1.11.2-1.1.jar) 
	UCHI	thejungle{1.0.1112} [Welcome to the Jungle] (Welcome to the Jungle-1.057b.1112.jar) 
	UCHI	denseores{1.0} [denseores] (denseores-1.11-1.0.2.jar) 
	UCHE	jaopca{1.11.2-1.1.18} [Just A Ore Processing Compatibility Attempt] (JAOPCA-1.11.2-1.1.18.jar) 
	UCHI	unidict{1.11.2-1.1b} [UniDict] (UniDict-1.11.2-1.1b.jar) 
	Loaded coremods (and transformers): 
DynamicSurroundingsCore (DynamicSurroundings-1.11.2-3.4.6.0.jar)
  org.blockartistry.DynSurround.asm.Transformer
LoadingPlugin (Quark-r1.2-93.jar)
  vazkii.quark.base.asm.ClassTransformer
IvToolkit (IvToolkit-1.3.3.jar)
  
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.7.1-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
CTMCorePlugin (CTM-MC1.11.2-0.2.1.10.jar)
  team.chisel.ctm.client.asm.CTMTransformer
CoFH Loading Plugin (CoFHCore-1.11.2-4.2.7.15-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CCLCorePlugin (CodeChickenLib-1.11.2-3.0.0.284-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
AstralCore (astralsorcery-1.4.5.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.53' Renderer: 'GeForce GTX 750/PCIe/SSE2'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)

	codechickenlib Invalid Fingerprint Reports: - No invalid fingerprints.: 
	chickenchunks Invalid Fingerprint Reports: - No invalid fingerprints.: 
```

**Comment by TheLMiffy1111** [comment]
Fixed.
