### ISSUE TITLE
[1.20.1] Crashed with new version of Electrodynamics

### ISSUE THREAD

**Issue by KalinZhang** [TheLMiffy1111/JAOPCA#289]
Hello
Electrodynamics recently released its 1.20.1 version and it seems to use a new version of JSON format so the current JAOPCA caused a crash. I can only load my save by disabling the integration for electrodynamics.
Below is part of the log:

Description: mouseClicked event handler

java.lang.UnsupportedOperationException: jaopca:electrodynamics.ore_to_dust.iesnium: You must include an operating tick time!
	at electrodynamics.common.recipe.ElectrodynamicsRecipeSerializer.getTicks(ElectrodynamicsRecipeSerializer.java:226) ~[Electrodynamics-1.20.1-0.9.0-0.jar%23520!/:1.20.1-0.9.0-0] {re:classloading}
	at electrodynamics.common.recipe.categories.item2item.Item2ItemRecipeSerializer.fromJson(Item2ItemRecipeSerializer.java:28) ~[Electrodynamics-1.20.1-0.9.0-0.jar%23520!/:1.20.1-0.9.0-0] {re:classloading}
	at electrodynamics.common.recipe.categories.item2item.Item2ItemRecipeSerializer.m_6729_(Item2ItemRecipeSerializer.java:17) ~[Electrodynamics-1.20.1-0.9.0-0.jar%23520!/:1.20.1-0.9.0-0] {re:classloading}
	at net.minecraftforge.common.extensions.IForgeRecipeSerializer.fromJson(IForgeRecipeSerializer.java:23) ~[forge-1.20.1-47.2.1-universal.jar%23701!/:?] {re:classloading}
	at net.minecraft.world.item.crafting.RecipeManager.fromJson(RecipeManager.java:171) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:67) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:34) ~[client-1.20.1-20230612.114412-srg.jar%23696!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
...

**Comment by TheLMiffy1111** [comment]
should be fixed
