### ISSUE TITLE
[1.7.10] Is log4j version too new?

### ISSUE THREAD

**Issue by msparkles** [TheLMiffy1111/JAOPCA#296]
*Using lwjgl3ify, might have affected this

Specifically, the versions after 0.4.11 crash with the following error:
```

cpw.mods.fml.common.LoaderException: java.lang.NoSuchMethodError: 'void org.apache.logging.log4j.Logger.info(java.lang.String, java.lang.Object)'
	at RFB-Launch//cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at RFB-Launch//cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:559)
	at RFB-Launch//cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:243)
	at RFB-Launch//net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at RFB-Launch//net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:8493)
	at RFB-Launch//net.minecraft.client.main.Main.main(SourceFile:148)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at RFB-System//net.minecraft.launchwrapper.Launch.realLaunch(Launch.java:248)
	at RFB-System//net.minecraft.launchwrapper.Launch.launch(Launch.java:35)
	at RFB-System//net.minecraft.launchwrapper.Launch.main(Launch.java:60)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.gtnewhorizons.retrofuturabootstrap.Main.main(Main.java:219)
	at RFB-System//org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
	at RFB-System//org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
	at RFB-System//org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoSuchMethodError: 'void org.apache.logging.log4j.Logger.info(java.lang.String, java.lang.Object)'
	at RFB-Launch//thelm.jaopca.modules.ModuleHandler.findModules(ModuleHandler.java:71)
	at RFB-Launch//thelm.jaopca.events.CommonEventHandler.onPreInit(CommonEventHandler.java:36)
	at RFB-Launch//thelm.jaopca.JAOPCA.onPreInit(JAOPCA.java:35)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at RFB-Launch//cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at RFB-System//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at RFB-System//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at RFB-System//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at RFB-System//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at RFB-System//com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at RFB-Launch//cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at RFB-Launch//cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at RFB-System//com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at RFB-System//com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at RFB-System//com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at RFB-System//com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at RFB-System//com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at RFB-Launch//cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at RFB-Launch//cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	... 15 more
```

And looking at the logs, it seems that an older version of log4j is used:
```
  /home/madeline/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.0-beta9-fixed/log4j-api-2.0-beta9-fixed.jar
  /home/madeline/.local/share/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.0-beta9-fixed/log4j-core-2.0-beta9-fixed.jar
```

**Comment by TheLMiffy1111** [comment]
Fixed in W.0.4.17

**Comment by steelshot** [comment]
Seems that this was reintroduced again in 1.7.10-W.0.5.20

https://mclo.gs/8XF5iex
