### ISSUE TITLE
Ic2 Issue

### ISSUE THREAD

**Issue by MinecraftArchive** [TheLMiffy1111/JAOPCA#4]
Caused by: java.lang.RuntimeException: The output ItemStack (null) is invalid.
 at ic2.core.recipe.BasicMachineRecipeManager.displayError(BasicMachineRecipeManager.java:275)
 at ic2.core.recipe.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:159)
 at ic2.core.recipe.BasicMachineRecipeManager.addRecipe(BasicMachineRecipeManager.java:36)
 at thelm.jaopca.modules.ModuleIndustrialCraft.addCentrifugeRecipe(ModuleIndustrialCraft.java:86)
 at thelm.jaopca.modules.ModuleIndustrialCraft.registerRecipes(ModuleIndustrialCraft.java:57)
 at thelm.jaopca.registry.RegistryCore.registerRecipes(RegistryCore.java:258)
 at thelm.jaopca.registry.RegistryCore.init(RegistryCore.java:65)
 at thelm.jaopca.JAOPCA.secondMovement(JAOPCA.java:64)

**Comment by MinecraftArchive** [comment]
Full Crash
[crash-2017-05-10_13.49.08-client.txt](https://github.com/TheLMiffy1111/JAOPCA/files/990783/crash-2017-05-10_13.49.08-client.txt)

**Comment by TheLMiffy1111** [comment]
I think it might be a config issue, let me see

**Comment by TheLMiffy1111** [comment]
I assume this is an issue with the config file, try deleting it

**Comment by MinecraftArchive** [comment]
i didn't even modify the config file its with ic2

**Comment by TheLMiffy1111** [comment]
The only way I could reproduce this issue is by changing the extra in the config file to an invalid ore name.
Anyways, try letting the config file regenerate.
I will add a check in the next version.

**Comment by TheLMiffy1111** [comment]
Should be fixed
