### ISSUE TITLE
[1.12.2] Crash with Foundry

### ISSUE THREAD

**Issue by ToMe25** [TheLMiffy1111/JAOPCA#82]
When i am trying to start Minecraft With JOAPCA and Foundry it Crashes.

Versions:
Minecraft Version: 1.12.2,
Forge Version: 14.23.4.2705,
CCL Version: 3.2.0.325,
CoFH Core Version: 4.5.2.19,
CoFH World Version: 1.2.0.5,
Foundry Version: 3.2.0,
JAOPCA Version: 2.2.8.90,
Jei Version: 4.11.0.202,
Placebo Version: 1.3.2,
Redstone Flux Version: 2.0.2.3,
Thermal Expansion Version: 5.5.0.29,
Thermal Foundation Version: 2.5.0.19,
Wrap Up Version: 1.1.3

**Crashlog**:

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 7/5/18 3:51 PM
Description: Initializing game

java.lang.NoSuchFieldError: instance
	at thelm.jaopca.modules.ModuleFoundry.preInit(ModuleFoundry.java:92)
	at thelm.jaopca.registry.RegistryCore.registerPreInit(RegistryCore.java:394)
	at thelm.jaopca.registry.RegistryCore.preInit1(RegistryCore.java:79)
	at thelm.jaopca.utils.JAOPCAEventHandler.onRegistryWrapUp(JAOPCAEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_72_JAOPCAEventHandler_onRegistryWrapUp_Event2.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at thelm.jaopca.modules.ModuleFoundry.preInit(ModuleFoundry.java:92)
	at thelm.jaopca.registry.RegistryCore.registerPreInit(RegistryCore.java:394)
	at thelm.jaopca.registry.RegistryCore.preInit1(RegistryCore.java:79)
	at thelm.jaopca.utils.JAOPCAEventHandler.onRegistryWrapUp(JAOPCAEventHandler.java:33)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_72_JAOPCAEventHandler_onRegistryWrapUp_Event2.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at thelm.wrapup.WrapUp.onVillagerProfessionRegisterLowest(WrapUp.java:99)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_WrapUp_onVillagerProfessionRegisterLowest_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:750)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-24-generic
	Java Version: 1.8.0_162, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 355583288 bytes (339 MB) / 1090375680 bytes (1039 MB) up to 4187619328 bytes (3993 MB)
	JVM Flags: 5 total; -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                | Version         | Source                                          | Signature                                |
	|:----- |:----------------- |:--------------- |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft         | 1.12.2          | minecraft.jar                                   | None                                     |
	| UCH   | mcp               | 9.42            | minecraft.jar                                   | None                                     |
	| UCH   | FML               | 8.0.99.99       | forge-1.12.2-14.23.4.2705.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge             | 14.23.4.2705    | forge-1.12.2-14.23.4.2705.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | codechickenlib    | 3.2.0.345       | CodeChickenLib-1.12.2-3.2.0.345-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | redstoneflux      | 2.0.2           | RedstoneFlux-1.12-2.0.2.3-universal.jar         | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | cofhcore          | 4.5.2           | CoFHCore-1.12.2-4.5.2.19-universal.jar          | None                                     |
	| UCH   | cofhworld         | 1.2.0           | CoFHWorld-1.12.2-1.2.0.5-universal.jar          | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | jei               | 4.11.0.202      | jei_1.12.2-4.11.0.202.jar                       | None                                     |
	| UCH   | placebo           | 1.3.2           | Placebo-1.12.2-1.3.2.jar                        | None                                     |
	| UCH   | thermalfoundation | 2.5.0           | ThermalFoundation-1.12.2-2.5.0.19-universal.jar | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | foundry           | 3.2.0           | Foundry-1.12.2-3.2.0.jar                        | None                                     |
	| UCH   | jaopca            | 1.12.2-2.2.8.90 | JAOPCA-1.12.2-2.2.8.90.jar                      | None                                     |
	| UCH   | oredictinit       | 1.12.2-2.2.1.68 | JAOPCA-1.12.2-2.2.8.90.jar                      | None                                     |
	| UCH   | thermalexpansion  | 5.5.0           | ThermalExpansion-1.12.2-5.5.0.29-universal.jar  | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCH   | wrapup            | 1.12-1.1.3      | WrapUp-1.12-1.1.3.jar                           | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'X.Org' Version: '3.0 Mesa 17.2.8' Renderer: 'AMD RS780 (DRM 2.50.0 / 4.15.0-24-generic, LLVM 5.0.0)'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2705
	LWJGL: 2.9.4
	OpenGL: AMD RS780 (DRM 2.50.0 / 4.15.0-24-generic, LLVM 5.0.0) GL version 3.0 Mesa 17.2.8, X.Org
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: RP
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD FX CPU

**Comment by TheLMiffy1111** [comment]
fixed
